<a href="https://colab.research.google.com/github/dikshap07/ML-Algorithms/blob/master/KNN_using_airbnbdata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import files
import pandas as pd
import numpy as np

In [148]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/wwg4pqgauhudwuqqfta24zbkhqscvz')

In [149]:
df.head()

        id  ... reviews_per_month
0  7087327  ...               NaN
1   975833  ...              2.11
2  8249488  ...              1.00
3  8409022  ...               NaN
4  8411173  ...               NaN

[5 rows x 92 columns]

In [150]:
df.shape

(3723, 92)

In [151]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'summary',
       'space', 'description', 'experiences_offered', 'neighborhood_overview',
       'notes', 'transit', 'thumbnail_url', 'medium_url', 'picture_url',
       'xl_picture_url', 'host_id', 'host_url', 'host_name', 'host_since',
       'host_location', 'host_about', 'host_response_time',
       'host_response_rate', 'host_acceptance_rate', 'host_is_superhost',
       'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood',
       'host_listings_count', 'host_total_listings_count',
       'host_verifications', 'host_has_profile_pic', 'host_identity_verified',
       'street', 'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'city', 'state', 'zipcode', 'market',
       'smart_location', 'country_code', 'country', 'latitude', 'longitude',
       'is_location_exact', 'property_type', 'room_type', 'accommodates',
       'bathrooms', 'bedrooms', 'beds', 'bed_type', 'amenities', 'square_feet',
       'price', 'weekly_price', 'monthly_price', 'security_deposit',
       'cleaning_fee', 'guests_included', 'extra_people', 'minimum_nights',
       'maximum_nights', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'first_review', 'last_review', 'review_scores_rating',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value', 'requires_license',
       'license', 'jurisdiction_names', 'instant_bookable',
       'cancellation_policy', 'require_guest_profile_picture',
       'require_guest_phone_verification', 'calculated_host_listings_count',
       'reviews_per_month'],
      dtype='object')

In [152]:
df = df[['accommodates','bathrooms','bedrooms','number_of_reviews','price']]

In [153]:
df.head()

   accommodates  bathrooms  bedrooms  number_of_reviews    price
0             4        1.0       1.0                  0  $160.00
1             6        3.0       3.0                 65  $350.00
2             1        2.0       1.0                  1   $50.00
3             2        1.0       1.0                  0   $95.00
4             4        1.0       1.0                  0   $50.00

In [154]:
df['price']  #data type = string, os we need to remove '$' and ',' amd comvert it to float

0       $160.00
1       $350.00
2        $50.00
3        $95.00
4        $50.00
         ...
3718    $135.00
3719     $79.00
3720    $275.00
3721    $179.00
3722    $110.00
Name: price, Length: 3723, dtype: object

In [155]:
df['price'] = df['price'].apply(lambda x:x.replace('$',''))
df['price'] = df['price'].apply(lambda x:x.replace(',',''))
df['price'] = df['price'].astype('float')

In [156]:
df['price'].head()

0    160.0
1    350.0
2     50.0
3     95.0
4     50.0
Name: price, dtype: float64

In [157]:
#to check if there are any null values :

df.isnull() 

#or

df.info()   #there are null values in 'bathrooms','bedrooms'

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3723 entries, 0 to 3722
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   accommodates       3723 non-null   int64
 1   bathrooms          3696 non-null   float64
 2   bedrooms           3702 non-null   float64
 3   number_of_reviews  3723 non-null   int64
 4   price              3723 non-null   float64
dtypes: float64(3), int64(2)
memory usage: 145.6 KB

In [158]:
df = df.dropna(axis = 0)

In [159]:
#splitting data into training and testing sets

def train_test_split(dataframe, n):  #    0<n< 1
  k = len(dataframe)

  df_train = dataframe.iloc[:int(n*k),:]
  df_test = dataframe.iloc[int(n*k):,:]

  return df_train, df_test

In [160]:
df_train, df_test = train_test_split(df,0.8)

In [161]:
print("Shape of training data set",df_train.shape)
print("Shape of test data set",df_test.shape)

Shape of training data set (2940, 5)
Shape of test data set (735, 5)

In [162]:
#function to get euclidean distance:

from math import sqrt

def euclidean_dist(row1,row2):

  k = len(row1)  #because we dont want to include the price column
  total_diff = 0
  for i in range(k):
    total_diff = total_diff + ((row1[i] - row2[i])**2)

    euclidean_dist = sqrt(total_diff)

    return euclidean_dist

In [176]:
def predicted_price(test_row,df_train):
  euclidean_distances = []   #getting euclidean distance of this test row with all rows of train set

  test_row = [20,4,1,1,2]
  
  for index,train_row in df_train[feature].iterrows():
    
    distance = euclidean_dist(test_row,train_row)
  #print(distance)

    euclidean_distances.append(distance)

  df_train['distances'] = euclidean_distances

  df_new = df_train.sort_values(by = ['distances'])

  nearest_neighbour_prices = df_new['price'].iloc[0:5]

  predicted_price = nearest_neighbour_prices.mean()
  
  return predicted_price

In [110]:
row = next(df_train.iterrows())[1]

In [113]:
for index,rows in df_train.iterrows():

  row = [rows.accommodates,	rows.bathrooms,	rows.bedrooms	,rows. number_of_reviews]

In [114]:
feature = ['accommodates', 'bedrooms', 'bathrooms', 'number_of_reviews']

In [182]:
for i, row in df_test[feature].iterrows():

  predict_price = predicted_price(row,df_train)
  print(predict_price,row)
  df_test.loc[i,'predicted_price'] = predict_price

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

751.8 accommodates         6.0
bedrooms             3.0
bathrooms            2.0
number_of_reviews    0.0
Name: 2985, dtype: float64
751.8 accommodates         3.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    1.0
Name: 2986, dtype: float64
751.8 accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    0.0
Name: 2987, dtype: float64
751.8 accommodates          4.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    14.0
Name: 2988, dtype: float64
751.8 accommodates         10.0
bedrooms              6.0
bathrooms             4.0
number_of_reviews     8.0
Name: 2989, dtype: float64
751.8 accommodates         2.0
bedrooms             0.0
bathrooms            1.0
number_of_reviews    8.0
Name: 2990, dtype: float64
751.8 accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    3.0
Name: 2991, dtype: float64
751.8 accommodates          2.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    35.0
Name: 2992, dtype: float64
751.8 accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    4.0
Name: 2993, dtype: float64
751.8 accommodates         1.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    6.0
Name: 2994, dtype: float64
751.8 accommodates         12.0
bedrooms              5.0
bathrooms             4.0
number_of_reviews     0.0
Name: 2995, dtype: float64
751.8 accommodates         4.0
bedrooms             2.0
bathrooms            2.0
number_of_reviews    0.0
Name: 2996, dtype: float64
751.8 accommodates          3.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    66.0
Name: 2997, dtype: float64
751.8 accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    4.0
Name: 2998, dtype: float64
751.8 accommodates         2.0
bedrooms             0.0
bathrooms            1.0
number_of_reviews    9.0
Name: 2999, dtype: float64
751.8 accommodates          2.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    56.0
Name: 3000, dtype: float64
751.8 accommodates         1.0
bedrooms             2.0
bathrooms            1.0
number_of_reviews    6.0
Name: 3001, dtype: float64
751.8 accommodates         2.0
bedrooms             0.0
bathrooms            1.0
number_of_reviews    0.0
Name: 3002, dtype: float64
751.8 accommodates          6.0
bedrooms              3.0
bathrooms             1.5
number_of_reviews    29.0
Name: 3003, dtype: float64
751.8 accommodates         2.0
bedrooms             0.0
bathrooms            1.0
number_of_reviews    2.0
Name: 3005, dtype: float64
751.8 accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    1.0
Name: 3006, dtype: float64
751.8 accommodates         2.0
bedrooms             1.0
bathrooms            1.5
number_of_reviews    2.0
Name: 3007, dtype: float64
751.8 accommodates          2.0
bedrooms              0.0
bathrooms             1.0
number_of_reviews    11.0
Name: 3008, dtype: float64
751.8 accommodates          4.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    38.0
Name: 3009, dtype: float64
751.8 accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    6.0
Name: 3010, dtype: float64
751.8 accommodates          3.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    84.0
Name: 3011, dtype: float64
751.8 accommodates          6.0
bedrooms              2.0
bathrooms             1.0
number_of_reviews    10.0
Name: 3012, dtype: float64
751.8 accommodates         2.0
bedrooms             0.0
bathrooms            1.0
number_of_reviews    0.0
Name: 3013, dtype: float64
751.8 accommodates          4.0
bedrooms              2.0
bathrooms             1.5
number_of_reviews    23.0
Name: 3014, dtype: float64
751.8 accommodates          2.0
bedrooms              1.0
bathrooms             1.5
number_of_reviews    16.0
Name: 3015, dtype: float64
751.8 accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    0.0
Name: 3016, dtype: float64
751.8 accommodates           8.0
bedrooms               3.0
bathrooms              1.0
number_of_reviews    138.0
Name: 3017, dtype: float64
751.8 accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    1.0
Name: 3018, dtype: float64
751.8 accommodates         4.0
bedrooms             0.0
bathrooms            1.0
number_of_reviews    7.0
Name: 3019, dtype: float64
751.8 accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    0.0
Name: 3020, dtype: float64
751.8 accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    4.0
Name: 3021, dtype: float64
751.8 accommodates         2.0
bedrooms             0.0
bathrooms            1.0
number_of_reviews    8.0
Name: 3022, dtype: float64
751.8 accommodates         2.0
bedrooms             0.0
bathrooms            1.0
number_of_reviews    4.0
Name: 3023, dtype: float64
751.8 accommodates         3.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    5.0
Name: 3024, dtype: float64
751.8 accommodates         3.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    3.0
Name: 3025, dtype: float64
751.8 accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    8.0
Name: 3026, dtype: float64
751.8 accommodates         4.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    2.0
Name: 3027, dtype: float64
751.8 accommodates         3.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    0.0
Name: 3028, dtype: float64
751.8 accommodates          2.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    21.0
Name: 3029, dtype: float64
751.8 accommodates         1.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    6.0
Name: 3030, dtype: float64
751.8 accommodates          2.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    14.0
Name: 3031, dtype: float64
751.8 accommodates         1.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    3.0
Name: 3032, dtype: float64
751.8 accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    0.0
Name: 3033, dtype: float64
751.8 accommodates         1.0
bedrooms             1.0
bathrooms            1.5
number_of_reviews    3.0
Name: 3034, dtype: float64
751.8 accommodates          4.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    52.0
Name: 3035, dtype: float64
751.8 accommodates         4.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    2.0
Name: 3036, dtype: float64
751.8 accommodates          3.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    20.0
Name: 3037, dtype: float64
751.8 accommodates         4.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    0.0
Name: 3038, dtype: float64
751.8 accommodates         6.0
bedrooms             2.0
bathrooms            2.0
number_of_reviews    0.0
Name: 3039, dtype: float64
751.8 accommodates         1.0
bedrooms             1.0
bathrooms            1.5
number_of_reviews    0.0
Name: 3040, dtype: float64
751.8 accommodates         1.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    2.0
Name: 3041, dtype: float64
751.8 accommodates         3.0
bedrooms             0.0
bathrooms            1.0
number_of_reviews    2.0
Name: 3042, dtype: float64
751.8 accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    2.0
Name: 3043, dtype: float64
751.8 accommodates          2.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    12.0
Name: 3044, dtype: float64
751.8 accommodates          5.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    92.0
Name: 3045, dtype: float64
751.8 accommodates         4.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    1.0
Name: 3046, dtype: float64
751.8 accommodates          6.0
bedrooms              2.0
bathrooms             2.0
number_of_reviews    22.0
Name: 3047, dtype: float64
751.8 accommodates         3.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    4.0
Name: 3048, dtype: float64
751.8 accommodates          2.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    14.0
Name: 3049, dtype: float64
751.8 accommodates         1.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    6.0
Name: 3050, dtype: float64
751.8 accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    5.0
Name: 3051, dtype: float64
751.8 accommodates          2.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    15.0
Name: 3052, dtype: float64
751.8 accommodates         2.0
bedrooms             0.0
bathrooms            1.0
number_of_reviews    0.0
Name: 3053, dtype: float64
751.8 accommodates          2.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    96.0
Name: 3054, dtype: float64
751.8 accommodates         8.0
bedrooms             4.0
bathrooms            3.5
number_of_reviews    5.0
Name: 3055, dtype: float64
751.8 accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    0.0
Name: 3056, dtype: float64
751.8 accommodates          2.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    46.0
Name: 3057, dtype: float64
751.8 accommodates         5.0
bedrooms             2.0
bathrooms            1.0
number_of_reviews    0.0
Name: 3058, dtype: float64
751.8 accommodates         1.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    0.0
Name: 3059, dtype: float64
751.8 accommodates         3.0
bedrooms             3.0
bathrooms            1.0
number_of_reviews    0.0
Name: 3060, dtype: float64
751.8 accommodates         4.0
bedrooms             2.0
bathrooms            2.0
number_of_reviews    1.0
Name: 3061, dtype: float64
751.8 accommodates         4.0
bedrooms             2.0
bathrooms            2.5
number_of_reviews    0.0
Name: 3062, dtype: float64
751.8 accommodates         4.0
bedrooms             2.0
bathrooms            2.0
number_of_reviews    8.0
Name: 3063, dtype: float64
751.8 accommodates         1.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    9.0
Name: 3064, dtype: float64
751.8 accommodates         1.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    9.0
Name: 3065, dtype: float64
751.8 accommodates         5.0
bedrooms             1.0
bathrooms            2.0
number_of_reviews    4.0
Name: 3066, dtype: float64
751.8 accommodates          2.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    16.0
Name: 3067, dtype: float64
751.8 accommodates          4.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    15.0
Name: 3068, dtype: float64
751.8 accommodates         6.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    0.0
Name: 3069, dtype: float64
751.8 accommodates          2.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    11.0
Name: 3070, dtype: float64
751.8 accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    0.0
Name: 3071, dtype: float64
751.8 accommodates          3.0
bedrooms              0.0
bathrooms             1.0
number_of_reviews    70.0
Name: 3072, dtype: float64
751.8 accommodates          2.0
bedrooms              0.0
bathrooms             1.0
number_of_reviews    19.0
Name: 3073, dtype: float64
751.8 accommodates         6.0
bedrooms             2.0
bathrooms            1.0
number_of_reviews    4.0
Name: 3074, dtype: float64
751.8 accommodates          6.0
bedrooms              2.0
bathrooms             1.0
number_of_reviews    18.0
Name: 3075, dtype: float64

KeyboardInterrupt: ignored

In [181]:
df_test.head()

      accommodates  bathrooms  ...  price  predicted_price
2985             6        2.0  ...  600.0            751.8
2986             3        1.0  ...  250.0            751.8
2987             2        1.0  ...   75.0            751.8
2988             4        1.0  ...   99.0            751.8
2989            10        4.0  ...  499.0            751.8

[5 rows x 6 columns]

In [ ]:
new_df = train_df.sort_values(by = ['distances'], inplace = True)

  nearest_neighbour_prices = new_df['price'].iloc[0:5]

  predicted_price = nearest_neighbour_prices.mean()

  return predicted_price

In [144]:
def predict_price(row,temp_df):
    distances = temp_df[feature] - row
    squared = np.square(distances)
    dist = squared.sum(axis=1)
    temp_df['distance'] = dist**0.5

    
    new_df = temp_df.sort_values('distance')
    nearest_neighbor_prices = new_df['price'].iloc[0:5]
    predicted_price = nearest_neighbor_prices.mean()
    return predicted_price

In [145]:
for i,row in df_test[feature].iterrows():
    predicted_price = predict_price(row,df_train)
    
    df_test.loc[i,'predicted_price'] = predicted_price

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [170]:
for index,train_row in df_train[feature].iterrows():
  print(train_row)

Streaming output truncated to the last 5000 lines.
bedrooms             1.0
bathrooms            1.0
number_of_reviews    0.0
Name: 1977, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    7.0
Name: 1978, dtype: float64
accommodates          4.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    31.0
Name: 1979, dtype: float64
accommodates          1.0
bedrooms              1.0
bathrooms             2.0
number_of_reviews    13.0
Name: 1980, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    0.0
Name: 1981, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    0.0
Name: 1982, dtype: float64
accommodates         6.0
bedrooms             3.0
bathrooms            2.0
number_of_reviews    2.0
Name: 1983, dtype: float64
accommodates         4.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    1.0
Name: 1984, dtype: float64
accommodates          2.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    96.0
Name: 1985, dtype: float64
accommodates          2.0
bedrooms              1.0
bathrooms             1.5
number_of_reviews    35.0
Name: 1986, dtype: float64
accommodates         6.0
bedrooms             3.0
bathrooms            2.5
number_of_reviews    5.0
Name: 1987, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    9.0
Name: 1988, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    0.0
Name: 1989, dtype: float64
accommodates          2.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    10.0
Name: 1990, dtype: float64
accommodates          1.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    22.0
Name: 1991, dtype: float64
accommodates         4.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    2.0
Name: 1992, dtype: float64
accommodates           2.0
bedrooms               1.0
bathrooms              1.0
number_of_reviews    121.0
Name: 1993, dtype: float64
accommodates         4.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    7.0
Name: 1994, dtype: float64
accommodates          2.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    22.0
Name: 1995, dtype: float64
accommodates         6.0
bedrooms             2.0
bathrooms            1.0
number_of_reviews    0.0
Name: 1996, dtype: float64
accommodates         1.0
bedrooms             0.0
bathrooms            1.0
number_of_reviews    1.0
Name: 1997, dtype: float64
accommodates         3.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    2.0
Name: 1998, dtype: float64
accommodates          1.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    21.0
Name: 1999, dtype: float64
accommodates          4.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    23.0
Name: 2000, dtype: float64
accommodates         8.0
bedrooms             3.0
bathrooms            2.5
number_of_reviews    1.0
Name: 2001, dtype: float64
accommodates          4.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    12.0
Name: 2002, dtype: float64
accommodates         2.0
bedrooms             0.0
bathrooms            1.0
number_of_reviews    2.0
Name: 2003, dtype: float64
accommodates         4.0
bedrooms             2.0
bathrooms            1.0
number_of_reviews    0.0
Name: 2004, dtype: float64
accommodates          6.0
bedrooms              3.0
bathrooms             2.5
number_of_reviews    21.0
Name: 2005, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.5
number_of_reviews    0.0
Name: 2006, dtype: float64
accommodates          6.0
bedrooms              3.0
bathrooms             1.5
number_of_reviews    13.0
Name: 2007, dtype: float64
accommodates         6.0
bedrooms             2.0
bathrooms            1.5
number_of_reviews    7.0
Name: 2008, dtype: float64
accommodates         6.0
bedrooms             3.0
bathrooms            2.5
number_of_reviews    0.0
Name: 2009, dtype: float64
accommodates         7.0
bedrooms             3.0
bathrooms            1.5
number_of_reviews    1.0
Name: 2010, dtype: float64
accommodates          3.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    35.0
Name: 2011, dtype: float64
accommodates          2.0
bedrooms              1.0
bathrooms             2.0
number_of_reviews    47.0
Name: 2012, dtype: float64
accommodates         4.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    1.0
Name: 2013, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    2.0
Name: 2014, dtype: float64
accommodates          4.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    13.0
Name: 2015, dtype: float64
accommodates         4.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    0.0
Name: 2016, dtype: float64
accommodates          2.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    34.0
Name: 2017, dtype: float64
accommodates          2.0
bedrooms              0.0
bathrooms             1.0
number_of_reviews    65.0
Name: 2018, dtype: float64
accommodates          6.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    12.0
Name: 2019, dtype: float64
accommodates         6.0
bedrooms             2.0
bathrooms            2.5
number_of_reviews    4.0
Name: 2020, dtype: float64
accommodates          4.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    90.0
Name: 2021, dtype: float64
accommodates         4.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    3.0
Name: 2022, dtype: float64
accommodates          3.0
bedrooms              2.0
bathrooms             1.0
number_of_reviews    10.0
Name: 2023, dtype: float64
accommodates         6.0
bedrooms             2.0
bathrooms            1.0
number_of_reviews    2.0
Name: 2024, dtype: float64
accommodates           5.0
bedrooms               2.0
bathrooms              1.0
number_of_reviews    195.0
Name: 2025, dtype: float64
accommodates         5.0
bedrooms             0.0
bathrooms            1.0
number_of_reviews    2.0
Name: 2026, dtype: float64
accommodates         5.0
bedrooms             2.0
bathrooms            1.5
number_of_reviews    1.0
Name: 2027, dtype: float64
accommodates         4.0
bedrooms             2.0
bathrooms            1.0
number_of_reviews    7.0
Name: 2028, dtype: float64
accommodates          4.0
bedrooms              2.0
bathrooms             2.0
number_of_reviews    20.0
Name: 2029, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    0.0
Name: 2030, dtype: float64
accommodates          2.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    76.0
Name: 2031, dtype: float64
accommodates         4.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    8.0
Name: 2032, dtype: float64
accommodates          2.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    23.0
Name: 2033, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    7.0
Name: 2034, dtype: float64
accommodates         6.0
bedrooms             1.0
bathrooms            2.5
number_of_reviews    0.0
Name: 2035, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    5.0
Name: 2036, dtype: float64
accommodates           2.0
bedrooms               1.0
bathrooms              1.0
number_of_reviews    227.0
Name: 2037, dtype: float64
accommodates          2.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    18.0
Name: 2038, dtype: float64
accommodates          1.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    14.0
Name: 2039, dtype: float64
accommodates         10.0
bedrooms              4.0
bathrooms             4.0
number_of_reviews     0.0
Name: 2040, dtype: float64
accommodates         8.0
bedrooms             3.0
bathrooms            1.5
number_of_reviews    0.0
Name: 2041, dtype: float64
accommodates          2.0
bedrooms              1.0
bathrooms             2.0
number_of_reviews    10.0
Name: 2042, dtype: float64
accommodates         6.0
bedrooms             2.0
bathrooms            2.0
number_of_reviews    3.0
Name: 2043, dtype: float64
accommodates          3.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    51.0
Name: 2044, dtype: float64
accommodates           2.0
bedrooms               1.0
bathrooms              1.0
number_of_reviews    180.0
Name: 2045, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    1.0
Name: 2046, dtype: float64
accommodates          5.0
bedrooms              3.0
bathrooms             2.5
number_of_reviews    17.0
Name: 2047, dtype: float64
accommodates          4.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    25.0
Name: 2048, dtype: float64
accommodates         4.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    2.0
Name: 2049, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    9.0
Name: 2050, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    0.0
Name: 2051, dtype: float64
accommodates           2.0
bedrooms               1.0
bathrooms              1.0
number_of_reviews    310.0
Name: 2052, dtype: float64
accommodates         6.0
bedrooms             3.0
bathrooms            2.5
number_of_reviews    2.0
Name: 2053, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    0.0
Name: 2054, dtype: float64
accommodates         3.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    3.0
Name: 2055, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    4.0
Name: 2056, dtype: float64
accommodates          3.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    41.0
Name: 2057, dtype: float64
accommodates          4.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    10.0
Name: 2058, dtype: float64
accommodates         6.0
bedrooms             2.0
bathrooms            1.5
number_of_reviews    0.0
Name: 2059, dtype: float64
accommodates          4.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    85.0
Name: 2060, dtype: float64
accommodates         4.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    2.0
Name: 2061, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    2.0
Name: 2062, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.5
number_of_reviews    1.0
Name: 2063, dtype: float64
accommodates          3.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    13.0
Name: 2064, dtype: float64
accommodates          2.0
bedrooms              1.0
bathrooms             1.5
number_of_reviews    10.0
Name: 2065, dtype: float64
accommodates          2.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    29.0
Name: 2066, dtype: float64
accommodates         8.0
bedrooms             3.0
bathrooms            2.5
number_of_reviews    9.0
Name: 2067, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    0.0
Name: 2068, dtype: float64
accommodates          4.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    11.0
Name: 2069, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.5
number_of_reviews    1.0
Name: 2070, dtype: float64
accommodates          4.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    21.0
Name: 2071, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    1.0
Name: 2072, dtype: float64
accommodates         11.0
bedrooms              5.0
bathrooms             4.5
number_of_reviews     0.0
Name: 2073, dtype: float64
accommodates          2.0
bedrooms              1.0
bathrooms             2.5
number_of_reviews    76.0
Name: 2074, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    4.0
Name: 2075, dtype: float64
accommodates          2.0
bedrooms              1.0
bathrooms             1.5
number_of_reviews    28.0
Name: 2076, dtype: float64
accommodates          2.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    10.0
Name: 2077, dtype: float64
accommodates           2.0
bedrooms               1.0
bathrooms              1.0
number_of_reviews    318.0
Name: 2078, dtype: float64
accommodates          2.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    74.0
Name: 2079, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.5
number_of_reviews    8.0
Name: 2080, dtype: float64
accommodates          2.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    28.0
Name: 2081, dtype: float64
accommodates          2.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    61.0
Name: 2082, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    0.0
Name: 2083, dtype: float64
accommodates         4.0
bedrooms             2.0
bathrooms            1.0
number_of_reviews    5.0
Name: 2084, dtype: float64
accommodates         2.0
bedrooms             0.0
bathrooms            1.0
number_of_reviews    1.0
Name: 2085, dtype: float64
accommodates         5.0
bedrooms             3.0
bathrooms            2.0
number_of_reviews    4.0
Name: 2086, dtype: float64
accommodates         6.0
bedrooms             3.0
bathrooms            1.5
number_of_reviews    2.0
Name: 2088, dtype: float64
accommodates          3.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    14.0
Name: 2089, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    0.0
Name: 2090, dtype: float64
accommodates          6.0
bedrooms              3.0
bathrooms             3.0
number_of_reviews    11.0
Name: 2091, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    4.0
Name: 2092, dtype: float64
accommodates          4.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    28.0
Name: 2093, dtype: float64
accommodates          4.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    28.0
Name: 2094, dtype: float64
accommodates          2.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    34.0
Name: 2095, dtype: float64
accommodates          6.0
bedrooms              3.0
bathrooms             1.5
number_of_reviews    11.0
Name: 2096, dtype: float64
accommodates          4.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    26.0
Name: 2097, dtype: float64
accommodates          3.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    47.0
Name: 2098, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.5
number_of_reviews    9.0
Name: 2099, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    1.0
Name: 2100, dtype: float64
accommodates         3.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    1.0
Name: 2101, dtype: float64
accommodates          2.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    51.0
Name: 2102, dtype: float64
accommodates         5.0
bedrooms             2.0
bathrooms            1.5
number_of_reviews    0.0
Name: 2103, dtype: float64
accommodates         2.0
bedrooms             0.0
bathrooms            1.0
number_of_reviews    4.0
Name: 2104, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    1.0
Name: 2105, dtype: float64
accommodates         15.0
bedrooms              6.0
bathrooms             4.5
number_of_reviews     0.0
Name: 2106, dtype: float64
accommodates         4.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    2.0
Name: 2107, dtype: float64
accommodates         4.0
bedrooms             1.0
bathrooms            2.5
number_of_reviews    1.0
Name: 2108, dtype: float64
accommodates         4.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    8.0
Name: 2109, dtype: float64
accommodates           4.0
bedrooms               1.0
bathrooms              1.0
number_of_reviews    142.0
Name: 2110, dtype: float64
accommodates           2.0
bedrooms               0.0
bathrooms              1.0
number_of_reviews    141.0
Name: 2111, dtype: float64
accommodates         6.0
bedrooms             3.0
bathrooms            1.0
number_of_reviews    0.0
Name: 2112, dtype: float64
accommodates          3.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    12.0
Name: 2113, dtype: float64
accommodates         4.0
bedrooms             2.0
bathrooms            1.0
number_of_reviews    0.0
Name: 2114, dtype: float64
accommodates         5.0
bedrooms             1.0
bathrooms            2.0
number_of_reviews    3.0
Name: 2115, dtype: float64
accommodates         5.0
bedrooms             2.0
bathrooms            1.5
number_of_reviews    3.0
Name: 2116, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.5
number_of_reviews    0.0
Name: 2117, dtype: float64
accommodates          5.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    43.0
Name: 2118, dtype: float64
accommodates         4.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    3.0
Name: 2119, dtype: float64
accommodates          4.0
bedrooms              2.0
bathrooms             2.5
number_of_reviews    36.0
Name: 2120, dtype: float64
accommodates          2.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    28.0
Name: 2121, dtype: float64
accommodates          3.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    25.0
Name: 2122, dtype: float64
accommodates          1.0
bedrooms              1.0
bathrooms             1.0
number_of_reviews    51.0
Name: 2123, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    1.0
Name: 2124, dtype: float64
accommodates         3.0
bedrooms             2.0
bathrooms            1.0
number_of_reviews    1.0
Name: 2125, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    6.0
Name: 2126, dtype: float64
accommodates         2.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    1.0
Name: 2127, dtype: float64
accommodates         4.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    1.0
Name: 2128, dtype: float64
accommodates         1.0
bedrooms             1.0
bathrooms            0.0
number_of_reviews    2.0
Name: 2129, dtype: float64
accommodates          6.0
bedrooms              2.0
bathrooms             2.5
number_of_reviews    17.0
Name: 2130, dtype: float64
accommodates         1.0
bedrooms             1.0
bathrooms            1.0
number_of_reviews    8.0
Name: 2131, dtype: float64
accommodates           2.0
bedrooms               1.0
bathrooms              1.5

In [175]:
euclidean_distances = []   #getting euclidean distance of this test row with all rows of train set

test_row = [20,4,1,1,2]
  
for index,train_row in df_train[feature].iterrows():
  
  distance = euclidean_dist(test_row,train_row)
  #print(distance)

  euclidean_distances.append(distance)

df_train['distances'] = euclidean_distances

df_new = df_train.sort_values(by = ['distances'])
df_new.head()

#nearest_neighbour_prices = df_new['price'].iloc[0:5]

#predicted_price = nearest_neighbour_prices.mean()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':

      accommodates  bathrooms  bedrooms  number_of_reviews   price  distances
1402            16        6.0       8.0                 10  1200.0        4.0
1596            16        3.5       5.0                  8   299.0        4.0
763             16        1.0       1.0                  0  1000.0        4.0
1594            16        8.0      10.0                  0  1250.0        4.0
1818            16        0.5       1.0                  0    10.0        4.0